version: 2.1

jobs:
  build-test-react:
    working_directory: ~/app/
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout:
          require_ssh_keys: true
      - run:
          name: Install packages
          command: cd ./ClientApp && npm install
      - run:
          name: Test
          command:  cd ./ClientApp && npm run test
      - run:
          name: Build Frontend
          command: cd ./ClientApp && npm run build
  build-test-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Restore packages
          command: dotnet restore
          working_directory: ./WebApi
      - run:
          name: Build project
          command: dotnet build
          working_directory: ./WebApi
      - run:
          name: Run tests
          command: dotnet test
          working_directory: ./WebApi.Test

workflows:
  stack:
    jobs:
      - build-test-react
      - build-test-dotnet