version: 2.1

orbs:
  node: circleci/node@5.1.0
  

jobs:
  build-test-react:
    executor: node/default
    working_directory: ./ClientApp
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout:
          path: ~/ClientApp
          require_ssh_keys: true
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Test
          command:  npm run test
      - run:
          name: Build Frontend
          command: npm run build
  build-test-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    working_directory: ./WebApi
    steps:
      - checkout
      - run:
          name: Restore packages
          command: dotnet restore
          working_directory: ./WebApi
      - run:
          name: Build project
          command: dotnet build
          working_directory: ./WebApi
      - run:
          name: Run tests
          command: dotnet test
          working_directory: ./WebApi.Test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  stack:
    jobs:
      - build-test-react
      - build-test-dotnet