const path = "./images/products/";

const products = [
    {
        id: 1,
        title: "Fifine USB Microphone",
        category: "microphone",
        description: "FIFINE USB Studio Recording Microphone Computer Podcast Mic for PC, PS4, Mac with Mute Button & Monitor Headphone Jack, Four Pickup Patterns for Vocals YouTube Streaming Gaming ASMR Zoom-Class (K690)",
        image: path + "Fifine-USB-Mic.jpg",
        price: 94.99,
        rating: 4.7,
        inStock: true,
        brand: "Fifine",
    },
    {
        id: 2,
        title: "Shinco Handheld Mic",
        category: "microphone",
        description: "Shinco Handheld Wired Microphone, Cardioid Dynamic Vocal Mic with 13ft Cable and ON/Off Switch, Ideally Suited for Speakers, Karaoke Singing Machine, Amp, Mixer",
        image: path + "Shinco-Handheld-mic.jpg",
        price: 15.99,
        rating: 4.2,
        inStock: true,
        brand: "Shinco",
    },
    {
        id: 3,
        title: "Blue Snowball",
        category: "microphone",
        description: "Blue Snowball iCE USB Microphone for PC, Mac, Gaming, Recording, Streaming, Podcasting, with Cardioid Condenser Mic Capsule, Adjustable Desktop Stand and USB cable, Plug 'n Play – Black",
        image: path + "blue-mic.jpg",
        price: 49.99,
        rating: 4.6,
        inStock: true,
        brand: "Blue",
    },
    {
        id: 4,
        title: "Fifine Gaming RGB Microphone",
        category: "microphone",
        description: "FIFINE Gaming USB Microphone for PC PS5, Condenser Mic with Quick Mute, RGB Indicator, Tripod Stand, Pop Filter, Shock Mount, Gain Control for Streaming Discord Twitch Podcasts Videos- AmpliGame",
        image: path + "rgb-gaming-mic.jpg",
        price: 34.99,
        rating: 4.4,
        inStock: true,
        brand: "Fifine",
    },
    {
        id: 5,
        title: "Soundcore Headphones",
        category: "headphones",
        description: "Soundcore Anker Life Q20 Hybrid Active Noise Cancelling Headphones, Wireless Over Ear Bluetooth Headphones, 40H Playtime, Hi-Res Audio, Deep Bass, Memory Foam Ear Cups, for Travel, Home Office",
        image: path + "soundcore-headphones.jpg",
        price: 59.99,
        rating: 4.5,
        inStock: true,
        brand: "Soundcore",
    },
    {
        id: 6,
        title: "Lorelei X6 Wired Headphones",
        category: "headphones",
        description: "Over-Ear Headphones with Microphone, Lightweight Foldable & Portable Stereo Bass Headphones with 1.45M No-Tangle, Wired Headphones for Smartphone Tablet MP3 / 4 (Space Black)",
        image: path + "lorelei-x6.jpg",
        price: 16.99,
        rating: 4.4,
        inStock: true,
        brand: "Lorelei",
    },
    {
        id: 7,
        title: "OneOdio Premium Brown/Silver Headphones",
        category: "headphones",
        description: "Over Ear Headphone, Wired Premium Stereo Sound Headsets with 50mm Driver, Foldable Comfortable Headphones with Protein Earmuffs and Shareport for Recording Monitoring Podcast PC TV- with Mic (Silver)",
        image: path + "brown-headphones.jpg",
        price: 40.99,
        rating: 4.6,
        inStock: true,
        brand: "OneOdio",
    },
    {
        id: 8,
        title: "Skullcandy Hesh ANC",
        category: "headphones",
        description: "Over-Ear Headphones, Active Noise Cancelling, Wireless Charging 22 Hours Battery Life - True Black",
        image: path + "skullcandies.jpg",
        price: 99.85,
        rating: 4.9,
        inStock: true,
        brand: "Skullcandy",
    },
    {
        id: 9,
        title: "LVY 3.5mm Audio Selector",
        category: "switch",
        description: "2 Way Audio Switcher; Headphone Switcher, Stereo AUX Audio Selector, AB Switcher Selector, Audio Sharing 2(1)-in-1(2)-Out",
        image: path + "lvy-2switch.jpg",
        price: 21.99,
        rating: 3.4,
        inStock: true,
        brand: "LVY",
    },
    {
        id: 10,
        title: "Tenealay 4 Way Switch",
        category: "switch",
        description: " 3.5mm Stereo Audio Switch Input Signal Source Switcher Selector Splitter Box with line Volume Controller（4 in 1 Out / 1 in 4 Out）-MC41",
        image: path + "tenealay-4switch.jpg",
        price: 19.89,
        rating: 4.1,
        inStock: true,
        brand: "Tenealay",
    },
    {
        id: 11,
        title: "Tenealay 3-in-1 Switch",
        category: "switch",
        description: "3.5mm Audio Switch with line Volume Controller, 3 in 1 Out 1/8\" aux switcher Splitter selector Box, Mini Inline Headphone attenuator Volume Control knob -MC31",
        image: path + "tenealay-3switch.jpg",
        price: 17.99,
        rating: 4.7,
        inStock: true,
        brand: "",
    },
    // {
    //     id: 30,
    //     title: "",
    //     category: "",
    //     description: "",
    //     image: path + "/",
    //     price: 94.99,
    //     rating: 4.7,
    //     inStock: true,
    //     brand: "",
    // },
];

export default products;